global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - prometheus:9090
  - job_name: 'postgres-exporter'
    scrape_interval: 5s
    static_configs:
    - targets:
      - postgres-exporter:9187
  - job_name: 'asp-net'
    scrape_interval: 5s
    static_configs:
    - targets:
      - app:8080
rule_files:
  - rules.yml
  
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: 
          - alertmanager:9093